# Use a Debian-based image with more complete build tools
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /new_file

# Copy the current directory contents into the container at /new_file
COPY . .

# Install necessary build tools and dependencies for Debian
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run the ETL script
CMD ["python", "ETL_Script.py"]
